site_name: AcessibilidadeJá
site_description: Documentação - Widget de Acessibilidade

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Início: index.md
  - Desenho de Software (Base): 
    - Base: Base/1.Base.md
    - Design Sprint: Base/1.1.DesignSprint.md
    - Artefato Generalista: Base/1.2.ArtefatoGeneralista.md
    - Modelagem BPMN: Base/1.3.ModelagemBPMN.md
    - Participacões: Base/1.4.ParticipacoesBase.md
    - Iniciativas Extras: Base/1.5.IniciativasExtras.md
